version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "7080:80"
    volumes:
      - ./components/app:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/log-volume/nginx:/var/log/nginx
    depends_on:
      - app
      - api
    links:
      - app
      - api

  app:
    restart: on-failure
    build:
      context: ./components/app
      dockerfile: ./Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./components/app:/app
    expose:
      - "19006"
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"

  api:
    restart: on-failure
    build:
      context: ./components/api
      dockerfile: ./Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./components/api:/api
      - bundle_cache:/usr/local/bundle
    expose:
      - "3000"
    ports:
      - "3080:3080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres@db/api_development
      TEST_DATABASE_URL: postgresql://postgres@db/api_test
      VHOST: "http://0.0.0.0:7080"

  db:
    image: postgres:latest
    volumes:
      - ./docker/data-volume/postgresql:/var/lib/postgresql/data
    ports:
      - 5456:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: api_development

volumes:
  bundle_cache:
